apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoApp
metadata:
  name: fraud-rules-engine
spec:
  replicas: 1
  build:
    gitSource:
      uri: "https://github.com/krnaraya/fraud-rules-engine.git"
    # set your maven nexus repository to speed up the build time
    #mavenMirrorURL: 